"""Curated model registry for MOYAG user-facing generation selectors.

Only expose models that are verified or intentionally enabled. Do not mirror the
full upstream DataEyes catalog into the product UI.
"""

CATALOG_MODELS = [
        {
            "id": "gpt-image-1",
            "name": "GPT Image 1",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": False,
            "tags": ["GPT变体", "已验证", "默认隐藏"],
        },
        {
            "id": "gpt-image-1-sp",
            "name": "GPT Image 1 SP",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": True,
            "tags": ["GPT变体", "已验证"],
        },
        {
            "id": "gpt-image-1.5",
            "name": "GPT Image 1.5",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": False,
            "tags": ["GPT变体", "已验证", "默认隐藏"],
        },
        {
            "id": "gpt-image-1.5-sp",
            "name": "GPT Image 1.5 SP",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": False,
            "tags": ["GPT变体", "已验证", "默认隐藏"],
        },
        {
            "id": "gpt-image-2",
            "name": "GPT Image 2",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": True,
            "tags": ["主图", "新模型"],
        },
        {
            "id": "gpt-image-2-sp",
            "name": "GPT Image 2 SP",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": False,
            "tags": ["GPT变体", "已验证", "默认隐藏"],
        },
        {
            "id": "imagen-4.0-generate-001",
            "name": "Imagen 4.0",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": True,
            "tags": ["主图", "细节增强"],
        },
        {
            "id": "grok-imagine-image",
            "name": "Grok Imagine",
            "category": "image",
            "format": "openai",
            "params": ["n"],
            "enabled": True,
            "tags": ["主图", "快速"],
        },
        {
            "id": "grok-imagine-image-pro",
            "name": "Grok Imagine Pro",
            "category": "image",
            "format": "openai",
            "params": ["n"],
            "enabled": False,
            "tags": ["已验证", "默认隐藏"],
        },
        {
            "id": "ByteDance-Seedream-4.0",
            "name": "Seedream 4.0",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": False,
            "tags": ["已验证", "默认隐藏"],
        },
        {
            "id": "ByteDance-Seedream-4.5",
            "name": "Seedream 4.5",
            "category": "image",
            "format": "openai_nosize",
            "params": ["n"],
            "enabled": False,
            "tags": ["已验证", "默认隐藏"],
        },
        {
            "id": "ByteDance-Seedream-5.0",
            "name": "Seedream 5.0",
            "category": "image",
            "format": "openai_nosize",
            "params": ["n"],
            "enabled": False,
            "tags": ["已验证", "默认隐藏"],
        },
        {
            "id": "doubao-seedream-4-0-250828",
            "name": "Doubao Seedream 4.0",
            "category": "image",
            "format": "openai",
            "params": ["size", "n"],
            "enabled": True,
            "tags": ["主图", "快速"],
        },
        {
            "id": "doubao-seedream-4-5-251128",
            "name": "Doubao Seedream 4.5",
            "category": "image",
            "format": "openai_nosize",
            "params": ["n"],
            "enabled": False,
            "tags": ["已验证", "默认隐藏"],
        },
        {
            "id": "doubao-seedream-5-0-260128",
            "name": "Doubao Seedream 5.0",
            "category": "image",
            "format": "openai_nosize",
            "params": ["n"],
            "enabled": False,
            "tags": ["已验证", "默认隐藏"],
        },
        # ── Gemini / NanoBanana models (Fix 2B) ──
        {
            "id": "gemini-2.5-flash-image",
            "name": "NanoBanana",
            "category": "image",
            "format": "nanobanana_openai",
            "params": ["n"],
            "enabled": True,
            "tags": ["主图", "兜底", "高速"],
        },
        {
            "id": "gemini-3-pro-image-preview",
            "name": "NanoBanana Pro",
            "category": "image",
            "format": "nanobanana_openai",
            "params": ["n"],
            "enabled": True,
            "tags": ["高质量", "4K"],
        },
        {
            "id": "gemini-3.1-flash-image-preview-4k",
            "name": "NanoBanana Flash 4K",
            "category": "image",
            "format": "nanobanana_openai",
            "params": ["n"],
            "enabled": False,
            "tags": ["4K", "已验证", "默认隐藏"],
        },
        {
            "id": "gemini-3.1-flash-image",
            "name": "NanoBanana Flash",
            "category": "image",
            "format": "nanobanana_openai",
            "params": ["n"],
            "enabled": True,
            "tags": ["高速", "低价"],
        },
        {
            "id": "gemini-2.5-flash-image-preview",
            "name": "NanoBanana Preview",
            "category": "image",
            "format": "nanobanana_openai",
            "params": ["n"],
            "enabled": False,
            "tags": ["预览", "已验证", "默认隐藏"],
        },
        # ── Video models (R5) ──
        {
            "id": "doubao-seedance-1-5-pro-251215",
            "name": "Seedance 1.5 Pro",
            "category": "video",
            "format": None,
            "params": ["resolution", "duration", "ratio"],
            "enabled": True,
            "vendor": "seedance",
            "async": True,
            "tags": ["视频", "通用", "已验证"],
        },
        {
            "id": "kling-v2-6",
            "name": "Kling 2.6",
            "category": "video",
            "format": None,
            "params": ["duration", "aspect_ratio", "mode"],
            "enabled": True,
            "vendor": "kling",
            "async": True,
            "tags": ["视频", "已验证"],
        },
        {
            "id": "kling-v3",
            "name": "Kling 3.0",
            "category": "video",
            "format": None,
            "params": ["duration", "aspect_ratio", "mode"],
            "enabled": True,
            "vendor": "kling",
            "async": True,
            "tags": ["视频", "已验证"],
        },
        {
            "id": "kling-v2-5-turbo",
            "name": "Kling 2.5 Turbo",
            "category": "video",
            "format": None,
            "params": ["duration", "aspect_ratio", "mode"],
            "enabled": True,
            "vendor": "kling",
            "async": True,
            "tags": ["视频", "已验证"],
        },
        {
            "id": "MiniMax-Hailuo-2.3",
            "name": "Hailuo 2.3",
            "category": "video",
            "format": None,
            "params": ["duration", "resolution"],
            "enabled": False,
            "vendor": "hailuo",
            "async": True,
            "tags": ["视频", "已验证"],
        },
        {
            "id": "viduq3-pro",
            "name": "Vidu Q3 Pro",
            "category": "video",
            "format": None,
            "params": ["duration", "aspect_ratio", "resolution"],
            "enabled": True,
            "vendor": "vidu",
            "async": True,
            "tags": ["视频", "已验证"],
        },
        {
            "id": "jimeng_t2v_v30",
            "name": "Jimeng T2V 3.0",
            "category": "video",
            "format": None,
            "params": ["frames", "aspect_ratio"],
            "enabled": False,
            "vendor": "jimeng",
            "async": True,
            "tags": ["视频", "已验证"],
        },
        {
            "id": "grok-imagine-video",
            "name": "Grok Video",
            "category": "video",
            "format": None,
            "params": ["duration", "aspect_ratio", "resolution"],
            "enabled": False,
            "vendor": "grok",
            "async": True,
            "tags": ["视频", "已验证"],
        },
]


def enabled_catalog() -> dict[str, list[dict]]:
    """Return only enabled models grouped by category. Always include all keys."""
    catalog: dict[str, list[dict]] = {"image": [], "video": [], "3d": []}
    for model in CATALOG_MODELS:
        if not model.get("enabled"):
            continue
        category = model.get("category")
        if category in catalog:
            catalog[category].append(dict(model))
        else:
            catalog[category] = [dict(model)]
    return catalog
